# -*- coding: utf-8 -*-
"""Retail Customer Analytics and Store Performance Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TSwWsZn3otri3CpdClNmovY1e06x6lA5

#Phase 1: Dataset Overview & Assessment
"""

import pandas as pd

df1 = pd.read_csv(r"/content/QVI_purchase_behaviour.csv")

df2 = pd.read_excel(r"/content/QVI_transaction_data.xlsx")

df_purchase = df1.copy()
df_transaction = df2.copy()

df_transaction.describe()

df_transaction.info()

df_transaction.head()

"""#Phase 2: Data Cleaning  """

df_purchase.duplicated().sum()

df_transaction.duplicated().sum()
df_transaction[df_transaction.duplicated(keep=False)]

df_transaction.drop_duplicates(inplace=True)

df_transaction["DATE"].dtype

# Convert Excel serial dates to datetime
df_transaction["DATE"] = pd.to_datetime(
    df_transaction["DATE"],
    unit="D",
    origin="1899-12-30"
)

df_transaction["DATE"].dtype

# Check the first few dates
df_transaction["DATE"].head()

# Check the date range
df_transaction["DATE"].agg(["min", "max"])

# Check unique years
df_transaction["DATE"].dt.year.unique()

# Check the months represented
df_transaction["DATE"].dt.month_name().unique()

"""#Phase 3: Data Quality Assessment"""

df_transaction[['LYLTY_CARD_NBR','TXN_ID']].head()

# Check if the columns are unique
df_transaction["TXN_ID"].is_unique

df_transaction["LYLTY_CARD_NBR"].is_unique

df_transaction["TXN_ID"].duplicated().sum()

df_transaction["LYLTY_CARD_NBR"].duplicated().sum()

duplicated_txn = df_transaction[df_transaction["TXN_ID"].duplicated(keep=False)]
duplicated_txn.head()

duplicated_txn["TXN_ID"].unique()[:10]

df_transaction[df_transaction["TXN_ID"] == 48887]

"""#Phase 4: Feature Engineering"""

df_transaction["Year"] = df_transaction["DATE"].dt.year

df_transaction["Month"] = df_transaction["DATE"].dt.month

df_transaction["Month_Name"] = df_transaction["DATE"].dt.month_name()

df_transaction["Quarter"] = df_transaction["DATE"].dt.quarter

# List of ID columns
id_columns = [
    "LYLTY_CARD_NBR",
    "TXN_ID",
    "STORE_NBR",
    "PROD_NBR",
    "TOT_SALES"
]

# Check for negative and zero values
for col in id_columns:
    print(f"\nColumn: {col}")
    print(f"Negative values: {(df_transaction[col] < 0).sum()}")
    print(f"Zero values: {(df_transaction[col] == 0).sum()}")
    print("-" * 40)

df_transaction["PROD_NAME"].unique()

df_purchase["LIFESTAGE"].unique()

df_purchase["PREMIUM_CUSTOMER"].unique()

"""#Feature Engineering"""

df_transaction["PROD_NAME"].tail(20)

df_transaction["PACKET_SIZE_G"] = df_transaction["PROD_NAME"].str.extract(r"(\d+)").astype(int)

df_transaction["PACKET_SIZE_G"].head(10)

brand_lookup = {
    "Smiths": "Smiths",
    "Smith": "Smiths",

    "Kettle": "Kettle",

    "Doritos": "Doritos",
    "Dorito": "Doritos",

    "Pringles": "Pringles",

    "Twisties": "Twisties",

    "CCs": "CCs",

    "Grain Waves": "Grain Waves",
    "GrnWves": "Grain Waves",

    "Natural Chip Co": "Natural Chip Co",
    "Natural ChipCo": "Natural Chip Co",
    "Natural Chip": "Natural Chip Co",

    "Old El Paso": "Old El Paso",

    "Red Rock Deli": "Red Rock Deli",
    "RRD": "Red Rock Deli",

    "Thins": "Thins",

    "Cheezels": "Cheezels",

    "Infuzions": "Infuzions",
    "Infzns": "Infuzions",

    "Cobs": "Cobs",

    "Woolworths": "Woolworths",
    "WW": "Woolworths",

    "Burger Rings": "Burger Rings",

    "French Fries": "French Fries",

    "Tostitos": "Tostitos",

    "Tyrrells": "Tyrrells",

    "Cheetos": "Cheetos",

    "Sunbites": "Sunbites",
    "Snbts": "Sunbites",

    "NCC": "NCC"
}

df_transaction[df_transaction["PROD_NAME"].str.contains("NCC")]

def extract_brand(product_name):
    for brand, standard_name in brand_lookup.items():
        if product_name.startswith(brand):
            return standard_name
    return "Unknown"

df_transaction["BRAND_NAME"] = df_transaction["PROD_NAME"].apply(extract_brand)

df_transaction["BRAND_NAME"].value_counts()

"""#Phase 4: Exploratory Data Analysis

##Section 1: Overall Business Overview
"""

df_transaction.head()

revenue = df_transaction["TOT_SALES"].sum()
print(f"Total Revenue: $ {revenue:.0f}")

transactions = df_transaction["TXN_ID"].sum()
print(f"Total Transactions: {transactions:.0f}")

df_transaction.head()

total_transactions = df_transaction["TXN_ID"].nunique()

print(f"Total Transactions: {total_transactions:,}")

total_units = df_transaction["PROD_QTY"].sum()
print(f"Total Units Sold: {total_units:,}")

avg_spend = revenue/total_transactions
print(f"Average Spend per Transaction: ${avg_spend:.2f}")

unique_customers = df_transaction["LYLTY_CARD_NBR"].nunique()

print(f"Unique Customers: {unique_customers:,}")

purchase_frequency = total_transactions/unique_customers
print(f"Purchase Frequecy: {purchase_frequency:1f}")

"""#Section 1: Product Analysis"""

#Which brands generate the most revenue?
df_transaction.groupby("BRAND_NAME")["TOT_SALES"].sum().sort_values(ascending=False)

#Which packet sizes are most popular?

df_transaction.groupby("PACKET_SIZE_G")["PROD_QTY"].sum().sort_values(ascending=False)

#Which packet sizes generate the most revenue?

df_transaction.groupby("PACKET_SIZE_G")["TOT_SALES"].sum().sort_values(ascending=False)

#Which products are purchased most frequently?

df_transaction.groupby("PROD_NAME")["TXN_ID"].count().sort_values(ascending=False)

"""#Section 2: Customer Analysis"""

df_transaction = df_transaction.merge(df_purchase, on="LYLTY_CARD_NBR", how="left")

df_transaction[["LYLTY_CARD_NBR", "LIFESTAGE", "PREMIUM_CUSTOMER"]].head()
df_transaction[["LIFESTAGE", "PREMIUM_CUSTOMER"]].isna().sum()

# Which customer segment buys the most chips?
customer_buys_more = df_transaction.groupby("LIFESTAGE")["PROD_QTY"].sum().sort_values(ascending=False)
customer_buys_more

# Which customer segment generates the most revenue?
customer_spends_more = df_transaction.groupby("LIFESTAGE")["TOT_SALES"].sum().sort_values(ascending=False)
customer_spends_more

# Which customer segment purchases most frequently?
customer_freq = df_transaction.groupby("LIFESTAGE")["TXN_ID"].count().sort_values(ascending=False)
customer_freq

# Which segment spends the most per transaction?
customer_spend_per_transaction = df_transaction.groupby("LIFESTAGE")["TOT_SALES"].sum() / df_transaction.groupby("LIFESTAGE")["TXN_ID"].count()
customer_spend_per_transaction.sort_values(ascending=False)

"""#Section 4: Purchasing Behaviour Analysis"""

# Which brands are preferred by each customer segment?
df_transaction.groupby(["LIFESTAGE", "BRAND_NAME"])["PROD_QTY"].sum().sort_values(ascending=False)

# Which packet sizes are preferred by each customer segment?
df_transaction.groupby(["LIFESTAGE", "PACKET_SIZE_G"])["PROD_QTY"].sum().sort_values(ascending=False)

# Do Premium customers spend more?
df_transaction.groupby("PREMIUM_CUSTOMER")["TOT_SALES"].sum().sort_values(ascending=False)

"""# Section 5: Sales Trend Analysis"""

df_transaction.columns

# Are there seasonal trends?
df_transaction.groupby("Month_Name")["TOT_SALES"].sum().sort_values(ascending=False)

# Which quarter generated the most revenue?
df_transaction.groupby("Quarter")["TOT_SALES"].sum().sort_values(ascending=False)

# Did sales improve over time?
monthly_units = (
    df_transaction.groupby("Month")["PROD_QTY"]
    .sum()
    .sort_index()
)

monthly_units

df_transaction["PACKET_SIZE_G"].unique()

df_transaction.to_csv("chip_sales_transaction.csv",index=False)